### ISSUE TITLE
Arms followMeArmExecution too close to Hip

### ISSUE THREAD

**Issue by munozyanez** [roboticslab-uc3m/follow-me#32]
During demo execution, arms swing is too close to hip with harm danger.

**Comment by munozyanez** [comment]
More precisely, after swing, while greeting, the opposite arm moves to a home position that is so close to hip.

**Comment by rsantos88** [comment]
Ok, this issue was resolved in this commit (762bffe495c8323ab669c70ba05e2c46b00314cf).
Now, I've increased speed and accelerations in other this (18e1094c5aa7830dd08ddebf70cf7734b80eec1c). It's shows more spectacular but you must to take care if you see something strange, or a wrong move. Take emergency stop buttons near!!

**Comment by jgvictores** [comment]
Yay! @rsantos88 Thanks!
